# Date 22/02/2025
**This is Day one of Machine lerning with python**

## Let's start from basics of python

In [1]:
# Let's start from basics of python

def main ():
    Basics()
    exception_handling()

def Basics():
    name = "Gaurav"
    roll = 50
    print(f"My name is {name} and Roll no. is {roll}")

# conditionals 
    x = "Yes"
    if x == "Yes":
        print("Hello guys")

# loops
    for _ in range(10):
        print(_, end="")
    x=1
    print("\n")
    while (x <= 10):
        print(x, end="")
        x +=1

    print("\n")

def exception_handling():
    
    try:
        no = int(input("Enter a char to see the error"))
    except ValueError:
        print("Yep!!, ValueError is working correctly")

    x = 10
    y = "Hello"
    try:
        ans = x + y 
    except TypeError:
        print("For addition both variables should be of same type")

    try:
        print("Using ZeroDivisionError")
        ans = x/0
    except ZeroDivisionError:
        print("Cannot divide by Zero")

# Other Errors
# 2. TypeError: Raised when an operation or function is applied to an object of inappropriate type.
# 3. IndexError: Raised when a sequence subscript is out of range.
# 4. KeyError: Raised when a dictionary key is not found.
# 5. AttributeError: Raised when an attribute reference or assignment fails.
# 6. ImportError: Raised when an import statement fails to find the module definition or when a from ... import fails to find a name that is to be imported.
# 7. IOError: Raised when an I/O operation (such as a file operation) fails.
# 8. ZeroDivisionError: Raised when the second argument of a division or modulo operation is zero.
# 9. FileNotFoundError: Raised when a file or directory is requested but doesn't exist.
# 10. RuntimeError: Raised when an error is detected that doesn't fall in any of the other categories.



if __name__ == "__main__":
    main()

My name is Gaurav and Roll no. is 50
Hello guys
0123456789

12345678910

Yep!!, ValueError is working correctly
For addition both variables should be of same type
Using ZeroDivisionError
Cannot divide by Zero


## Data Structures

### Lists  []

In [2]:
names = ["Gaurav", "Shoham", "Piyush", "Kallu"]
print("\nprinting Using Loop")
for name in names:
    print(name, end =" ")
print("\nPrinting Using *(asterisk)")
print(*names, sep= ", ")

# adding elements
names.append("hello")
names.insert(1, "byee")
# Added hello and byee
print(*names, sep= ", ")




printing Using Loop
Gaurav Shoham Piyush Kallu 
Printing Using *(asterisk)
Gaurav, Shoham, Piyush, Kallu
Gaurav, byee, Shoham, Piyush, Kallu, hello


In [3]:
# popping element
names.pop()
names.pop(0)

print("\n Popped last element and Gaurav\n",*names, sep= ", ")

names.remove("byee")
print("\nremoved byee \n",*names, sep= ", ")




 Popped last element and Gaurav
, byee, Shoham, Piyush, Kallu

removed byee 
, Shoham, Piyush, Kallu


In [4]:
# Sorting
print("\nSorting")
names.sort() # names.sort(reverse=True) for desending order
print(*names, sep= ", ")



Sorting
Kallu, Piyush, Shoham


In [5]:
# reversing the string (not sorting)
print("\nReversed list is")
names.reverse()
print(*names)



Reversed list is
Shoham Piyush Kallu


In [6]:
# adding one list into other
stud_name = ["Gaurav", "Sayali"]
names.extend(stud_name)
print(*names)

Shoham Piyush Kallu Gaurav Sayali


In [7]:
# Finding Index
print("Piyush is at index:",names.index("Piyush"))

Piyush is at index: 1


In [8]:
# Counting specific element in list
print(names.count("Piyush"))

1


In [9]:
# Clearing the List
print(names.clear())

None


### Dictionary  {Key, Value}

In [10]:
# get(): Returns the value for a specified key if the key is in the dictionary.
dit = {"Name": "Gaurav", "Roll No:" : 50 }
print(dit)


{'Name': 'Gaurav', 'Roll No:': 50}


In [11]:

# printing using loops
print("\nPrinting using loops")
for key,value in dit.items():
    print(f"{key}:{value}")

print("\nPrinting Specific key, values")
print(f"keys are:{dit.keys()}")
print(f"Values are:{dit.values()}")



Printing using loops
Name:Gaurav
Roll No::50

Printing Specific key, values
keys are:dict_keys(['Name', 'Roll No:'])
Values are:dict_values(['Gaurav', 50])


In [12]:

# Using List Comprension
print("\nPrinting Using list Comprension")
print("\n".join([f"{key}: {value}" for key, value in dit.items()]))


Printing Using list Comprension
Name: Gaurav
Roll No:: 50


### Tupple ()

**Tuples in Python are immutable, so they have fewer methods compared to lists. However, there are still some common methods and operations that you can perform with tuples. Here are the most common ones:**

In [13]:
tp = (1,2,3,"gaurav")
print(*tp)

1 2 3 gaurav


In [14]:
# Accessing elements via index
print(tp[3])

gaurav


In [15]:
# Slicing
print("Elements at index 1-3 are:",tp[1:4])

Elements at index 1-3 are: (2, 3, 'gaurav')


In [16]:
# Length of tupple
print("Length is:",len(tp))

Length is: 4


**Membersip: Checking if an element is in a tuple.**

In [17]:
print(2 in tp)

True


**Unpacking: Assigning elements of a tuple to variables.**

In [18]:
name = ("gaurav", "Patil")
first, last = name
print("First name:", first, ", Surname:",last)

First name: gaurav , Surname: Patil


In [19]:
#  Count
print(tp.count(2))

1


### Sets {}

**Sets in Python are unordered collections of unique elements.**

***Repetition or same elements are removed autometically***

**Add element in set**

In [20]:
set1 = {1,2,3, "Gaurav"}
print(*set1)
set1.add(4)
print(*set1)

1 2 3 Gaurav
1 2 3 4 Gaurav


**Remove using remove(), it gives error if element is not found**

In [21]:
set1.remove(2)
print(*set1)

1 3 4 Gaurav


**Remove using discard(), ***it wont raise an error if element is not found*****

In [22]:
set1.discard(2)
set1

{1, 3, 4, 'Gaurav'}

**popping an arbitary element**


In [23]:
set1.pop()
set1

{3, 4, 'Gaurav'}

**Union, intersection, difference, symmetric difference, is upperset, is disjoint set**

***difference() returns a new set with elements in the set that are not in the others.***

***super subset: set A is considered a superset of set B if all elements of B are also elements of A.***

***disjoint() : it returns True if no elements are common else False***

In [24]:
set2 = {1,2,3}
set3 = {1,2,3,4,5}
print("union is",set2.union(set3))

print("intersection is:",set2.intersection(set3))
 
print("Difference :",set3.difference(set2) )

print("Symmetric Difference is:",set2.symmetric_difference(set3) )

print("Is set2 subset of set3: ",set2.issubset(set3))

print("Is set2 super subset of set3: ",set2.issuperset(set3))

print("Is set2 disjoint of set3: ",set2.isdisjoint(set3))


union is {1, 2, 3, 4, 5}
intersection is: {1, 2, 3}
Difference : {4, 5}
Symmetric Difference is: {4, 5}
Is set2 subset of set3:  True
Is set2 super subset of set3:  False
Is set2 disjoint of set3:  False


### Stack (LIFO)

#### using list

**It has T.C = O(n) for appending and popping**

In [25]:
#  Adding values

stack1 = []
stack1.append(10)
stack1.append(100)
stack1.append(110)

stack1

[10, 100, 110]

In [26]:
# popping last elements

stack1.pop()
stack1

[10, 100]

In [27]:
# Peeking

print(stack1[1])


100


In [28]:
#  size

print(len(stack1))

2


#### using dequeu from collectiom

**It has T.C = O(1) for appending and popping better than using list**

In [29]:
from collections import deque

stack2 = deque()

stack2.append(10)
stack2.append(20)
stack2.append(30)
stack2.append(40)

print(*stack2)


10 20 30 40


In [30]:
stack2.pop() # pop rightmost or last in element

40

In [31]:
stack2.rotate()
stack2

deque([30, 10, 20])

#### from queue import LifoQueue

**cannot view ele directly**


In [32]:
from queue import LifoQueue

stack3 = LifoQueue(maxsize= 3)

print(stack3.qsize())

stack3.put(10)
stack3.put(120)
stack3.put(110)

print("size is: 1",stack3.qsize())

print(stack3.get())
print(stack3.get())


0
size is: 1 3
110
120


### Queue

#### Using list similar to Stack using list

**Difference is we always pop(0)**

#### using dque similar to stack

**Difference is we always popleft()**


#### from queue import Queue

In [33]:
from queue import Queue
q = Queue(maxsize = 3)
print(q.qsize()) 
q.put('a')
q.put('b')
q.put('c')
print("\nFull: ", q.full()) 
print("\nElements dequeued from the queue")
print(q.get())
print(q.get())
print(q.get())

print("\nEmpty: ", q.empty())
q.put(1)

print("\nEmpty: ", q.empty()) 

print("Full: ", q.full())

0

Full:  True

Elements dequeued from the queue
a
b
c

Empty:  True

Empty:  False
Full:  False


**We can also use linked list as stack and queue**

In [34]:
# for stack

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class Stack:
    def __init__(self):
        self.head = None

    def is_empty(self):
        return self.head is None

    def push(self, data):
        new_node = Node(data)
        new_node.next = self.head
        self.head = new_node

    def pop(self):
        if self.is_empty():
            return None
        popped_node = self.head
        self.head = self.head.next
        return popped_node.data

    def peek(self):
        if self.is_empty():
            return None
        return self.head.data

    def display(self):
        current = self.head
        while current:
            print(current.data, end=" -> ")
            current = current.next
        print("None")

# Example usage
stack = Stack()
stack.push(10)
stack.push(20)
stack.push(30)
stack.display()  # Output: 30 -> 20 -> 10 -> None
print("Top element is:", stack.peek())  # Output: Top element is: 30
print("Popped element is:", stack.pop())  # Output: Popped element is: 30
stack.display()  # Output: 20 -> 10 -> None

30 -> 20 -> 10 -> None
Top element is: 30
Popped element is: 30
20 -> 10 -> None


In [35]:
# for queue
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class Queue:
    def __init__(self):
        self.front = None
        self.rear = None

    def is_empty(self):
        return self.front is None

    def enqueue(self, data):
        new_node = Node(data)
        if self.rear is None:
            self.front = self.rear = new_node
            return
        self.rear.next = new_node
        self.rear = new_node

    def dequeue(self):
        if self.is_empty():
            return None
        dequeued_node = self.front
        self.front = self.front.next
        if self.front is None:
            self.rear = None
        return dequeued_node.data

    def peek(self):
        if self.is_empty():
            return None
        return self.front.data

    def display(self):
        current = self.front
        while current:
            print(current.data, end=" -> ")
            current = current.next
        print("None")

# Example usage
queue = Queue()
queue.enqueue(10)
queue.enqueue(20)
queue.enqueue(30)
queue.display()  # Output: 10 -> 20 -> 30 -> None
print("Front element is:", queue.peek())  # Output: Front element is: 10
print("Dequeued element is:", queue.dequeue())  # Output: Dequeued element is: 10
queue.display()  # Output: 20 -> 30 -> None

10 -> 20 -> 30 -> None
Front element is: 10
Dequeued element is: 10
20 -> 30 -> None


## File Handling

In [36]:
with open("newdata.txt","w") as file:
    file.write("Hello, this is Gaurav Patil")


In [37]:
with open("newdata.txt", "r") as file:
    content = file.read()
    print(content)

Hello, this is Gaurav Patil


In [38]:
import json

# Read data from the file
with open('newdata.txt', 'r') as file:
    data = file.read()

# Convert the data to JSON format
data_json = json.dumps(data)

# Print the JSON data
print(data_json)

"Hello, this is Gaurav Patil"


## Numpy

- It is python library used for numerical computing, providing support for multidimensional arrays.
- Numpy uses less memory.
- Better for data preprocessing.
- It stores data in contiguous space, which makes it efficient in computations.


**dtype: int**

- 32-bit Integer Range: -2,147,483,648 to 2,147,483,647.
- 64-bit Integer Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.
  
**float**

- 32-bit Float Range: Approximately -3.4e38 to 3.4e38.
Precision: 7 decimal places.
- 64-bit Float Range: Approximately -1.8e308 to 1.8e308.
Precision: 15 decimal places.

**Axis**
- 1D array = 1 axis
- 2D array = 2 axis (1 = horizontal, 0 = vertical)
- 3D array = 3 axis (1 = horizontal, 0 = vertical, 2 = )


In [39]:
import numpy as np 
array1 = np.array([1,2,3], dtype= np.int32)
print("1D array is:", array1)
array2 = np.array([[1,2,3],[4,5,6]], dtype= np.int32)
print("2D array is:", array2)
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype= np.int32)
print("3D array is:\n", array3)

# Float

array4 = np.array([1,2,3], dtype= np.float32)
print("1D array is:", array4)



1D array is: [1 2 3]
2D array is: [[1 2 3]
 [4 5 6]]
3D array is:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1D array is: [1. 2. 3.]


In [40]:
# Steps for all info about arrays
print("dytpe of array1:",array1.dtype)
print("Shape of array1:",array1.shape)
print("size of array1:",array1.size)


dytpe of array1: int32
Shape of array1: (3,)
size of array1: 3


In [41]:
# Boolean
bol = np.array([True, False, True, False], dtype=np.bool_)
print("Boolean array is:", bol)

Boolean array is: [ True False  True False]


In [42]:
# String & object 


strr = np.array(["apple", "banana", "grapes"], dtype=np.str_)
print("String array is:", strr)

objectt = np.array([True,1, "Apple"], dtype=np.object_)
print("object Array is:",objectt)

String array is: ['apple' 'banana' 'grapes']
object Array is: [True 1 'Apple']


In [43]:
# changing elements
print(array1)
array1[0] = 4
print("after changing value",array1)

# for 2D
array2 = np.array([[1,2,3],[4,5,6]], dtype= np.int32)
print(array2)
array2[0,1] =4 #arr[row, column]
print("After changing values\n",array2) 

[1 2 3]
after changing value [4 2 3]
[[1 2 3]
 [4 5 6]]
After changing values
 [[1 4 3]
 [4 5 6]]


In [44]:
# functions
arangee = np.arange(10)
print("arange() is similar to range():\n",arangee) 

zero_arr = np.zeros((2,5), dtype= np.int32) 
print("\narray of zero\n",zero_arr)

one = np.ones((2,6), dtype = np.int32)
print("\nArray of 1's:\n",one)

identity = np.eye(2)
print("\nIdentity matrix is:\n",identity)

line_space = np.linspace(2, 3, 3)
print("\nLinespace will cerate no of elements (start, end, elements) with same spacing:\n",line_space)

arr = np.random.rand(3, 3)
print("\nCreate an of given shape and pupulate it within range(0-1):\n",arr)

arr = np.random.randn(3, 3)
print("\nCreate an of given shape and pupulate it with standard normal distribution:\n",arr)

total = np.sum(identity) # we can specify axis too
print("Sum of all elements in array",total)

total = np.mean(identity) # we can specify axis too
print("Mean of all elements in array",total)



arange() is similar to range():
 [0 1 2 3 4 5 6 7 8 9]

array of zero
 [[0 0 0 0 0]
 [0 0 0 0 0]]

Array of 1's:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]]

Identity matrix is:
 [[1. 0.]
 [0. 1.]]

Linespace will cerate no of elements (start, end, elements) with same spacing:
 [2.  2.5 3. ]

Create an of given shape and pupulate it within range(0-1):
 [[0.37977017 0.60837869 0.34614124]
 [0.67612231 0.3474325  0.85529674]
 [0.03798106 0.61118975 0.14736058]]

Create an of given shape and pupulate it with standard normal distribution:
 [[-1.17936097 -0.29018979 -0.42798619]
 [-1.34469906 -0.750247   -0.40343113]
 [-0.69248442  0.8067021   0.01722392]]
Sum of all elements in array 2.0
Mean of all elements in array 0.5


In [45]:
# methods
array2 = np.array([[8,5,2],[6,4,5]])
print("array2 is",array2)
array2 = array2.reshape((3,2))
print("rehaped array is:\n",array2)

sort = np.sort(array2)
print("sorted array is:\n",sort)

transpose = sort.transpose()
print("Transpose of sort is:\n",transpose)

array2 is [[8 5 2]
 [6 4 5]]
rehaped array is:
 [[8 5]
 [2 6]
 [4 5]]
sorted array is:
 [[5 8]
 [2 6]
 [4 5]]
Transpose of sort is:
 [[5 2 4]
 [8 6 5]]


In [46]:
# Attributes
print(array2)
print("shape",array2.shape)
print("data type",array2.dtype)
print("Size",array2.size)
print("no of dimensions",array2.ndim)
print("No of bytes consumed",array2.nbytes)

[[8 5]
 [2 6]
 [4 5]]
shape (3, 2)
data type int32
Size 6
no of dimensions 2
No of bytes consumed 24


## Pandas

 **Series & DataFrame**
- series is one dimension array with index, 
it has single column.
- DataFrame is multidimensional array,
it can store multiple columns

 **Axis**

- 1D array = 1 axis
- 2D array = 2 axis (1 = horizontal, 0 = vertical)
- 3D array = 3 axis (1 = horizontal, 0 = vertical, 2 = )


In [47]:
import pandas as pd

data ={
    "Names" :["Gaurav","Sujal","Atharva","Soham","piyush","Deepraj",pd.NA],
    "City" : ["Kolhapur","Kolhapur","Kolhapur","Satara","sangli","Pune",pd.NA]
}


df = pd.DataFrame(data)

df.to_csv("StudetInfo.csv",index = False)
read_df = pd.read_csv("StudetInfo.csv")
print(read_df)


     Names      City
0   Gaurav  Kolhapur
1    Sujal  Kolhapur
2  Atharva  Kolhapur
3    Soham    Satara
4   piyush    sangli
5  Deepraj      Pune
6      NaN       NaN


**------------------------Methods-----------------------------**

In [48]:

print("\nDescription is:\n",read_df.describe())



Description is:
          Names      City
count        6         6
unique       6         4
top     Gaurav  Kolhapur
freq         1         3


In [49]:

print(read_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Names   6 non-null      object
 1   City    6 non-null      object
dtypes: object(2)
memory usage: 244.0+ bytes
None


In [50]:
read_df.head()

Names      City
0   Gaurav  Kolhapur
1    Sujal  Kolhapur
2  Atharva  Kolhapur
3    Soham    Satara
4   piyush    sangli

In [51]:
read_df.tail(2)

Names  City
5  Deepraj  Pune
6      NaN   NaN

In [52]:
read_df.drop([4],axis = 0)

Names      City
0   Gaurav  Kolhapur
1    Sujal  Kolhapur
2  Atharva  Kolhapur
3    Soham    Satara
5  Deepraj      Pune
6      NaN       NaN

In [53]:
read_df.isna().sum()

Names    1
City     1
dtype: int64

In [54]:
read_df.dropna(inplace=True)
print("NaN values are dropped in orignal dataset too")

NaN values are dropped in orignal dataset too


In [55]:
read_df['City'].fillna(read_df['City'].mode()[0], inplace=True)
read_df

C:\Users\gaura\AppData\Local\Temp\ipykernel_18648\4219372018.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  read_df['City'].fillna(read_df['City'].mode()[0], inplace=True)


Names      City
0   Gaurav  Kolhapur
1    Sujal  Kolhapur
2  Atharva  Kolhapur
3    Soham    Satara
4   piyush    sangli
5  Deepraj      Pune

In [56]:
read_df.iloc[0,0] = "Gaurav Patil"
read_df

Names      City
0  Gaurav Patil  Kolhapur
1         Sujal  Kolhapur
2       Atharva  Kolhapur
3         Soham    Satara
4        piyush    sangli
5       Deepraj      Pune

In [ ]:
read_df.loc[1, 'Names'] = 'Sujal Patkare'

# saving updated dataframe into file
read_df.to_csv('StudetInfo.csv',index=False)
print("File Saved successfully")
read_df


File Saved successfully


Names      City
0   Gaurav Patil  Kolhapur
1  Sujal Patkare  Kolhapur
2        Atharva  Kolhapur
3          Soham    Satara
4         piyush    sangli
5        Deepraj      Pune

In [60]:
# Copy of old dataframe

new_df = read_df.copy()
new_df

Names      City
0   Gaurav Patil  Kolhapur
1  Sujal Patkare  Kolhapur
2        Atharva  Kolhapur
3          Soham    Satara
4         piyush    sangli
5        Deepraj      Pune

In [ ]:
# DataFrame to Numpy array
new_df.to_numpy()

array([['Gaurav Patil', 'Kolhapur'],
       ['Sujal Patkare', 'Kolhapur'],
       ['Atharva', 'Kolhapur'],
       ['Soham', 'Satara'],
       ['piyush', 'sangli'],
       ['Deepraj', 'Pune']], dtype=object)

In [65]:
read_df.drop([2,2],inplace=True)

In [ ]:
# sort via index

read_df.sort_index(axis=0,ascending=False)

Names      City
5        Deepraj      Pune
4         piyush    sangli
3          Soham    Satara
1  Sujal Patkare  Kolhapur
0   Gaurav Patil  Kolhapur

In [67]:
# sort via columns
read_df.sort_index(axis = 1,ascending=True)

City          Names
0  Kolhapur   Gaurav Patil
1  Kolhapur  Sujal Patkare
3    Satara          Soham
4    sangli         piyush
5      Pune        Deepraj

In [73]:
read_df.sort_values(by=['Names'],ascending=True,na_position='last')

Names      City
5        Deepraj      Pune
0   Gaurav Patil  Kolhapur
3          Soham    Satara
1  Sujal Patkare  Kolhapur
4         piyush    sangli

In [75]:
read_df.reset_index(drop = True, inplace=True)
read_df

Names      City
0   Gaurav Patil  Kolhapur
1  Sujal Patkare  Kolhapur
2          Soham    Satara
3         piyush    sangli
4        Deepraj      Pune

**----------------------Attributes---------------------**

In [ ]:
print("\nDatatype is:\n",read_df.dtypes)


Datatype is:
 Names    object
City     object
dtype: object


In [ ]:
read_df.index

Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [ ]:
read_df.columns

Index(['Names', 'City'], dtype='object')

In [ ]:
# Transpose
read_df.T

0              1         2       3       4        5
Names  Gaurav Patil  Sujal Patkare   Atharva   Soham  piyush  Deepraj
City       Kolhapur       Kolhapur  Kolhapur  Satara  sangli     Pune